# Generated by Django 3.2.15 on 2022-10-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_lga', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='lga_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_lga_results', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='pollingunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.CharField(max_length=100)),
                ('lga_id', models.CharField(max_length=100)),
                ('state_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pollngresults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_pu_results', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_wards', models.CharField(max_length=10000)),
            ],
        ),
    ]
