# Generated by Django 3.2.15 on 2022-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='wards',
            field=models.ManyToManyField(to='pollingapp.Ward'),
        ),
        migrations.AddField(
            model_name='ward',
            name='pollingunit',
            field=models.ManyToManyField(to='pollingapp.pollingunit'),
        ),
    ]
