# Generated by Django 3.2.15 on 2022-10-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapp', '0002_auto_20221026_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pollngresults',
            new_name='pollingresults',
        ),
    ]
